imports:
  - { resource: config.yml }

services:
  _defaults:
    public: false

  OpenCFP\Test\Helper\MockAuthentication:
    decorates: OpenCFP\Domain\Services\Authentication
    arguments: ['@OpenCFP\Test\Helper\MockAuthentication.inner']

  OpenCFP\Test\Helper\MockIdentityProvider:
    decorates: OpenCFP\Domain\Services\IdentityProvider
    arguments: ['@OpenCFP\Test\Helper\MockIdentityProvider.inner']

  # Compatibility for integration tests that still expect the service IDs as Silex registers them.
  csrf.token_manager:
    alias: security.csrf.token_manager
    public: true

  url_generator:
    alias: router
    public: true

framework:
  session:
    storage_id: session.storage.mock_file
  test: ~

swiftmailer:
  disable_delivery: true
