services:
  _defaults:
    public: false
    autowire: true

  OpenCFP\Console\Command\:
    resource: '%kernel.project_dir%/classes/Console/Command/*'
    tags:
      - { name: console.command }

  OpenCFP\Console\Application:
    public: true
    autowire: false
    calls:
      - [setDispatcher, ['@event_dispatcher']]
      - [add, ['@OpenCFP\Console\Command\UserCreateCommand']]
      - [add, ['@OpenCFP\Console\Command\UserDemoteCommand']]
      - [add, ['@OpenCFP\Console\Command\UserPromoteCommand']]
