language: php

sudo: false

env:
  global:
    - TRAVIS_DB=cfp_test
    - CODECLIMATE_REPO_TOKEN=9deb249b01a414d979959cfd05a4c351b19a5959858653b20276454d4189edc3

# cache composer downloads so installing is quicker
cache:
  yarn: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

stages:
  - style
  - test

jobs:
  include:
    - stage: Style

      php: 7.0

      before_install:
        - phpenv config-rm xdebug.ini
        - composer validate --no-check-publish

      install:
        - composer install

      before_script:
        - mkdir -p "$HOME/.php-cs-fixer"

      script:
        - vendor/bin/php-cs-fixer fix --diff --dry-run --verbose

    - stage: Test

      php: 7.0

      addons:
        apt:
          sources:
            - travis-ci/sqlite3
          packages:
            - sqlite3

      before_install:
        - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" ]]; then WITH_COVERAGE=true; else WITH_COVERAGE=false; fi
        - if [[ "$WITH_COVERAGE" == "false" ]]; then phpenv config-rm xdebug.ini; fi
        - composer validate --no-check-publish

      install:
        - composer install

      before_script:
        - sh tools/travis/setup-mail.sh
        - mysql -e "CREATE DATABASE $TRAVIS_DB" -uroot
        - cp phinx.yml.dist phinx.yml
        - vendor/bin/phinx migrate -e testing

      script:
        - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; else vendor/bin/phpunit; fi

      after_success:
        - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/test-reporter --coverage-report build/logs/clover.xml; fi
