
sudo: false

env:
  global:
    - TRAVIS_DB=cfp_test
    - CC_TEST_REPORTER_ID=9deb249b01a414d979959cfd05a4c351b19a5959858653b20276454d4189edc3

# cache composer downloads so installing is quicker
cache:
  yarn: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

stages:
  - style
  - test
  - asset

jobs:
  include:
    - stage: Style

      language: php

      php: 7.0

      before_install:
        - phpenv config-rm xdebug.ini
        - composer validate --no-check-publish

      install:
        - composer install

      before_script:
        - mkdir -p "$HOME/.php-cs-fixer"

      script:
        - vendor/bin/php-cs-fixer fix --diff --dry-run --verbose

    - &TEST

      stage: Test

      language: php

      php: 7.0

      addons:
        apt:
          sources:
            - travis-ci/sqlite3
          packages:
            - sqlite3

      before_install:
        - source .travis/xdebug.sh
        - xdebug-disable
        - composer validate --no-check-publish

      install:
        - composer install

      before_script:
        - source .travis/code-climate.sh
        - sh .travis/setup-mail.sh
        - mysql -e "CREATE DATABASE $TRAVIS_DB" -uroot
        - cp phinx.yml.dist phinx.yml
        - vendor/bin/phinx migrate -e testing
        - if [[ "$WITH_COVERAGE" == "true" ]]; then code-climate-before-script; fi

      script:
        - vendor/bin/phpunit --configuration tests/Integration/phpunit.xml.dist
        - if [[ "$WITH_COVERAGE" == "true" ]]; then xdebug-enable; fi
        - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/phpunit --configuration tests/Unit/phpunit.xml.dist --coverage-clover build/logs/clover.xml; else vendor/bin/phpunit --configuration tests/Unit/phpunit.xml.dist; fi
        - if [[ "$WITH_COVERAGE" == "true" ]]; then xdebug-disable; fi

      after_script:
        - if [[ "$WITH_COVERAGE" == "true" ]]; then code-climate-after-script; fi

    - <<: *TEST

      php: 7.1

      env:
        - WITH_COVERAGE=true

    - stage: Asset

      language: node_js

      node_js: 8.8.1

      install:
        - yarn install

      script:
        - yarn run production
