language: php

sudo: false

php:
  - 7.0
  - 5.6
  - 5.5

env:
  global:
    - TRAVIS_DB=cfp_travis
    - CODECLIMATE_REPO_TOKEN=9deb249b01a414d979959cfd05a4c351b19a5959858653b20276454d4189edc3

# cache composer downloads so installing is quicker
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer validate --no-check-publish

install:
  - composer install

before_script:
  - sh tools/travis/setup-mail.sh
  - mysql -e "CREATE DATABASE $TRAVIS_DB" -uroot
  - vendor/bin/phinx --configuration=phinx.yml.dist migrate -e testing

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/php-cs-fixer fix --verbose

after_script:
  - vendor/bin/test-reporter --coverage-report build/logs/clover.xml
