application:
  title: OpenCFP
  url: http://localhost
  email: contact@openconf.com
  eventurl: http://localhost
  event_location: Miami, FL
  enddate: Oct. 14th, 2018
  show_submission_count: false
  airport: MIA
  arrival: 2014-10-26
  departure: 2014-10-31
  secure_ssl: false
  online_conference: false
  date_format: m-d-Y


api:
  enabled: true

cache:
  enabled: false

database:
  host:
  database: "testdb.sqlite"
  dsn: "sqlite:testdb.sqlite"
  user:
  password:

log:
  level: debug

mail:
  host: ~
  port: ~
  username: ~
  password: ~
  encryption: ~
  auth_mode: ~
